package main

import (
	"go/format"
	"log"
	"os"
	"strings"
	"time"

	"github.com/ryanmab/rdap-go/internal/cmd/internal/bootstrap"
	"github.com/ryanmab/rdap-go/internal/model"
)

func main() {
	bootstrapResponse := bootstrap.FetchBootstrap(model.DomainQuery)

	log.Printf("Fetched DNS bootstrap data version %s published at %s. There are %d services", bootstrapResponse.Version, bootstrapResponse.Publication, len(bootstrapResponse.Services))

	f, err := os.Create("internal/registry/dns/bootstrap_generated.go")

	if err != nil {
		log.Fatal(err)
	}

	template, err := generate(bootstrapResponse)

	if err != nil {
		log.Fatal(err)
	}

	if _, err := f.Write(template); err != nil {
		log.Fatal(err)
	}

	if err := f.Close(); err != nil {
		log.Fatal(err)
	}

	log.Printf("Wrote DNS bootstrap data to internal/dns/bootstrap_generated.go")
}

// Generate the Go source code for the DNS bootstrap map based on the fetched data
// from IANA.
func generate(bootstrapResponse bootstrap.Response) ([]byte, error) {
	var sb strings.Builder
	for _, service := range bootstrapResponse.Services {
		for _, tld := range service.Keys {
			sb.WriteString("\t\t\"" + tld + "\": {\n")
			for _, server := range service.Servers {
				sb.WriteString("\t\t\t\"" + server + "\",\n")
			}
			sb.WriteString("\t\t},\n")
		}
	}

	template := []byte(`
		package dns

        // DO NOT EDIT!
		//
		// This file is generated by internal/cmd/generate-dns-bootstrap.go

		// Bootstrap is the DNS RDAP bootstrap data sourced from IANA.
		//
		// Source (version: ` + bootstrapResponse.Version + `, publication date: ` + bootstrapResponse.Publication.Format(time.RFC3339) + `): https://data.iana.org/rdap/dns.json
		var Bootstrap = map[string][]string{
			` + sb.String() + `
		}
	`)
	return format.Source(template)
}
