package ipv6

// DO NOT EDIT!
//
// This file is generated by internal/cmd/ipv6/main.go

// BootstrapAccessOrder is the IPv6 RDAP bootstrap data listed in descending order of specificity of IP range.
//
// The ordering is important to ensure that the most specific ranges are checked first during lookups.
var BootstrapAccessOrder = []string{
	"2620::/23",
	"2610::/23",
	"2001:4c00::/23",
	"2001:4a00::/23",
	"2001:4800::/23",
	"2001:4600::/23",
	"2001:4400::/23",
	"2001:4200::/23",
	"2001:4000::/23",
	"2001:1a00::/23",
	"2001:1800::/23",
	"2001:1200::/23",
	"2001:e00::/23",
	"2001:c00::/23",
	"2001:600::/23",
	"2001:400::/23",
	"2001:200::/23",
	"2001:1c00::/22",
	"2001:1400::/22",
	"2001:800::/22",
	"2001:b000::/20",
	"2001:a000::/20",
	"2001:5000::/20",
	"2001:8000::/19",
	"2001:2000::/19",
	"2003::/18",
	"2c00::/12",
	"2a10::/12",
	"2a00::/12",
	"2800::/12",
	"2630::/12",
	"2600::/12",
	"2410::/12",
	"2400::/12",
}

// Bootstrap is the IPv6 RDAP bootstrap data sourced from IANA.
//
// Source (version: 1.0, publication date: 2024-11-01T22:00:01Z): https://data.iana.org/rdap/ipv6.json
var Bootstrap = map[string][]string{
	"2001:4200::/23": {
		"https://rdap.afrinic.net/rdap/",
		"http://rdap.afrinic.net/rdap/",
	},
	"2c00::/12": {
		"https://rdap.afrinic.net/rdap/",
		"http://rdap.afrinic.net/rdap/",
	},
	"2001:200::/23": {
		"https://rdap.apnic.net/",
	},
	"2001:4400::/23": {
		"https://rdap.apnic.net/",
	},
	"2001:8000::/19": {
		"https://rdap.apnic.net/",
	},
	"2001:a000::/20": {
		"https://rdap.apnic.net/",
	},
	"2001:b000::/20": {
		"https://rdap.apnic.net/",
	},
	"2001:c00::/23": {
		"https://rdap.apnic.net/",
	},
	"2001:e00::/23": {
		"https://rdap.apnic.net/",
	},
	"2400::/12": {
		"https://rdap.apnic.net/",
	},
	"2410::/12": {
		"https://rdap.apnic.net/",
	},
	"2001:1800::/23": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2001:400::/23": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2001:4800::/23": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2600::/12": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2610::/23": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2620::/23": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2630::/12": {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	"2001:1400::/22": {
		"https://rdap.db.ripe.net/",
	},
	"2001:1a00::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:1c00::/22": {
		"https://rdap.db.ripe.net/",
	},
	"2001:2000::/19": {
		"https://rdap.db.ripe.net/",
	},
	"2001:4000::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:4600::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:4a00::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:4c00::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:5000::/20": {
		"https://rdap.db.ripe.net/",
	},
	"2001:600::/23": {
		"https://rdap.db.ripe.net/",
	},
	"2001:800::/22": {
		"https://rdap.db.ripe.net/",
	},
	"2003::/18": {
		"https://rdap.db.ripe.net/",
	},
	"2a00::/12": {
		"https://rdap.db.ripe.net/",
	},
	"2a10::/12": {
		"https://rdap.db.ripe.net/",
	},
	"2001:1200::/23": {
		"https://rdap.lacnic.net/rdap/",
	},
	"2800::/12": {
		"https://rdap.lacnic.net/rdap/",
	},
}
