package asn

// DO NOT EDIT!
//
// This file is generated by internal/cmd/asn/main.go

// Bootstrap is the ASN RDAP bootstrap data sourced from IANA.
//
// Source (version: 1.0, publication date: 2025-11-19T20:00:02Z): https://data.iana.org/rdap/asn.json
var Bootstrap = map[[2]uint32][]string{
	{36864, 37887}: {
		"https://rdap.afrinic.net/rdap/",
		"http://rdap.afrinic.net/rdap/",
	},
	{327680, 328703}: {
		"https://rdap.afrinic.net/rdap/",
		"http://rdap.afrinic.net/rdap/",
	},
	{328704, 329727}: {
		"https://rdap.afrinic.net/rdap/",
		"http://rdap.afrinic.net/rdap/",
	},
	{4608, 4865}: {
		"https://rdap.apnic.net/",
	},
	{7467, 7722}: {
		"https://rdap.apnic.net/",
	},
	{9216, 10239}: {
		"https://rdap.apnic.net/",
	},
	{17408, 18431}: {
		"https://rdap.apnic.net/",
	},
	{23552, 24575}: {
		"https://rdap.apnic.net/",
	},
	{37888, 38911}: {
		"https://rdap.apnic.net/",
	},
	{45056, 46079}: {
		"https://rdap.apnic.net/",
	},
	{55296, 56319}: {
		"https://rdap.apnic.net/",
	},
	{58368, 59391}: {
		"https://rdap.apnic.net/",
	},
	{63488, 63999}: {
		"https://rdap.apnic.net/",
	},
	{64000, 64098}: {
		"https://rdap.apnic.net/",
	},
	{64297, 64395}: {
		"https://rdap.apnic.net/",
	},
	{131072, 132095}: {
		"https://rdap.apnic.net/",
	},
	{132096, 133119}: {
		"https://rdap.apnic.net/",
	},
	{133120, 133631}: {
		"https://rdap.apnic.net/",
	},
	{133632, 134556}: {
		"https://rdap.apnic.net/",
	},
	{134557, 135580}: {
		"https://rdap.apnic.net/",
	},
	{135581, 136505}: {
		"https://rdap.apnic.net/",
	},
	{136506, 137529}: {
		"https://rdap.apnic.net/",
	},
	{137530, 138553}: {
		"https://rdap.apnic.net/",
	},
	{138554, 139577}: {
		"https://rdap.apnic.net/",
	},
	{139578, 140601}: {
		"https://rdap.apnic.net/",
	},
	{140602, 141625}: {
		"https://rdap.apnic.net/",
	},
	{141626, 142649}: {
		"https://rdap.apnic.net/",
	},
	{142650, 143673}: {
		"https://rdap.apnic.net/",
	},
	{143674, 144697}: {
		"https://rdap.apnic.net/",
	},
	{144698, 145721}: {
		"https://rdap.apnic.net/",
	},
	{145722, 146745}: {
		"https://rdap.apnic.net/",
	},
	{146746, 147769}: {
		"https://rdap.apnic.net/",
	},
	{147770, 148793}: {
		"https://rdap.apnic.net/",
	},
	{148794, 149817}: {
		"https://rdap.apnic.net/",
	},
	{149818, 150841}: {
		"https://rdap.apnic.net/",
	},
	{150842, 151865}: {
		"https://rdap.apnic.net/",
	},
	{151866, 152889}: {
		"https://rdap.apnic.net/",
	},
	{152890, 153913}: {
		"https://rdap.apnic.net/",
	},
	{153914, 154937}: {
		"https://rdap.apnic.net/",
	},
	{154938, 155961}: {
		"https://rdap.apnic.net/",
	},
	{1, 1876}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{1902, 2042}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2044, 2046}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2048, 2106}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2137, 2584}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2615, 2772}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2823, 2829}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{2880, 3153}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{3354, 4607}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{4866, 5376}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{5632, 6655}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{6912, 7466}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{7723, 8191}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{10240, 12287}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{13312, 15359}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{16384, 17407}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{18432, 20479}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{21504, 23455}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{23457, 23551}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{25600, 26623}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{26624, 27647}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{29696, 30719}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{31744, 32767}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{32768, 33791}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{35840, 36863}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{39936, 40959}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{46080, 47103}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{53248, 54271}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{54272, 55295}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{62464, 63487}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{64198, 64296}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{393216, 394239}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{394240, 395164}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{395165, 396188}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{396189, 397212}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{397213, 398236}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{398237, 399260}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{399261, 400284}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{400285, 401308}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{401309, 402332}: {
		"https://rdap.arin.net/registry/",
		"http://rdap.arin.net/registry/",
	},
	{1877, 1901}: {
		"https://rdap.db.ripe.net/",
	},
	{2043, 2043}: {
		"https://rdap.db.ripe.net/",
	},
	{2047, 2047}: {
		"https://rdap.db.ripe.net/",
	},
	{2107, 2136}: {
		"https://rdap.db.ripe.net/",
	},
	{2585, 2614}: {
		"https://rdap.db.ripe.net/",
	},
	{2773, 2822}: {
		"https://rdap.db.ripe.net/",
	},
	{2830, 2879}: {
		"https://rdap.db.ripe.net/",
	},
	{3154, 3353}: {
		"https://rdap.db.ripe.net/",
	},
	{5377, 5631}: {
		"https://rdap.db.ripe.net/",
	},
	{6656, 6911}: {
		"https://rdap.db.ripe.net/",
	},
	{8192, 9215}: {
		"https://rdap.db.ripe.net/",
	},
	{12288, 13311}: {
		"https://rdap.db.ripe.net/",
	},
	{15360, 16383}: {
		"https://rdap.db.ripe.net/",
	},
	{20480, 21503}: {
		"https://rdap.db.ripe.net/",
	},
	{24576, 25599}: {
		"https://rdap.db.ripe.net/",
	},
	{28672, 29695}: {
		"https://rdap.db.ripe.net/",
	},
	{30720, 31743}: {
		"https://rdap.db.ripe.net/",
	},
	{33792, 34815}: {
		"https://rdap.db.ripe.net/",
	},
	{34816, 35839}: {
		"https://rdap.db.ripe.net/",
	},
	{38912, 39935}: {
		"https://rdap.db.ripe.net/",
	},
	{40960, 41983}: {
		"https://rdap.db.ripe.net/",
	},
	{41984, 43007}: {
		"https://rdap.db.ripe.net/",
	},
	{43008, 44031}: {
		"https://rdap.db.ripe.net/",
	},
	{44032, 45055}: {
		"https://rdap.db.ripe.net/",
	},
	{47104, 48127}: {
		"https://rdap.db.ripe.net/",
	},
	{48128, 49151}: {
		"https://rdap.db.ripe.net/",
	},
	{49152, 50175}: {
		"https://rdap.db.ripe.net/",
	},
	{50176, 51199}: {
		"https://rdap.db.ripe.net/",
	},
	{51200, 52223}: {
		"https://rdap.db.ripe.net/",
	},
	{56320, 57343}: {
		"https://rdap.db.ripe.net/",
	},
	{57344, 58367}: {
		"https://rdap.db.ripe.net/",
	},
	{59392, 60415}: {
		"https://rdap.db.ripe.net/",
	},
	{60416, 61439}: {
		"https://rdap.db.ripe.net/",
	},
	{61952, 62463}: {
		"https://rdap.db.ripe.net/",
	},
	{64396, 64495}: {
		"https://rdap.db.ripe.net/",
	},
	{196608, 197631}: {
		"https://rdap.db.ripe.net/",
	},
	{197632, 198655}: {
		"https://rdap.db.ripe.net/",
	},
	{198656, 199679}: {
		"https://rdap.db.ripe.net/",
	},
	{199680, 200191}: {
		"https://rdap.db.ripe.net/",
	},
	{200192, 201215}: {
		"https://rdap.db.ripe.net/",
	},
	{201216, 202239}: {
		"https://rdap.db.ripe.net/",
	},
	{202240, 203263}: {
		"https://rdap.db.ripe.net/",
	},
	{203264, 204287}: {
		"https://rdap.db.ripe.net/",
	},
	{204288, 205211}: {
		"https://rdap.db.ripe.net/",
	},
	{205212, 206235}: {
		"https://rdap.db.ripe.net/",
	},
	{206236, 207259}: {
		"https://rdap.db.ripe.net/",
	},
	{207260, 208283}: {
		"https://rdap.db.ripe.net/",
	},
	{208284, 209307}: {
		"https://rdap.db.ripe.net/",
	},
	{209308, 210331}: {
		"https://rdap.db.ripe.net/",
	},
	{210332, 211355}: {
		"https://rdap.db.ripe.net/",
	},
	{211356, 212379}: {
		"https://rdap.db.ripe.net/",
	},
	{212380, 213403}: {
		"https://rdap.db.ripe.net/",
	},
	{213404, 214427}: {
		"https://rdap.db.ripe.net/",
	},
	{214428, 215451}: {
		"https://rdap.db.ripe.net/",
	},
	{215452, 216475}: {
		"https://rdap.db.ripe.net/",
	},
	{27648, 28671}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{52224, 53247}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{61440, 61951}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{64099, 64197}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{262144, 263167}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{263168, 263679}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{263680, 264604}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{264605, 265628}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{265629, 266652}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{266653, 267676}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{267677, 268700}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{268701, 269724}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{269725, 270748}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{270749, 271772}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{271773, 272796}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{272797, 273820}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{273821, 274844}: {
		"https://rdap.lacnic.net/rdap/",
	},
	{274845, 275868}: {
		"https://rdap.lacnic.net/rdap/",
	},
}
