package main

import (
	"errors"
	"go/format"
	"log"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/ryanmab/rdap-go/internal/cmd/internal/bootstrap"
	"github.com/ryanmab/rdap-go/internal/model"
)

func main() {
	bootstrapResponse := bootstrap.FetchBootstrap(model.IPv4Query)

	log.Printf("Fetched IPv4 bootstrap data version %s published at %s. There are %d services", bootstrapResponse.Version, bootstrapResponse.Publication, len(bootstrapResponse.Services))

	f, err := os.Create("internal/registry/ipv4/bootstrap_generated.go")

	if err != nil {
		log.Fatal(err)
	}

	template, err := generate(bootstrapResponse)

	if err != nil {
		log.Fatal(err)
	}

	if _, err := f.Write(template); err != nil {
		log.Fatal(err)
	}

	if err := f.Close(); err != nil {
		log.Fatal(err)
	}

	log.Printf("Successfully generated internal/ipv4/bootstrap_generated.go")
}

// Generate the Go source code for the IPv4 bootstrap map based on the fetched data
// from IANA.
func generate(bootstrapResponse bootstrap.Response) ([]byte, error) {
	r := regexp.MustCompile(`([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})/([0-9]+)`)

	var sb strings.Builder
	for _, service := range bootstrapResponse.Services {
		for _, ip := range service.Keys {
			matches := r.FindStringSubmatch(ip)

			if matches == nil {
				return nil, errors.New("Invalid IP range format: " + ip)
			}

			ipParts := matches[1 : len(matches)-1]
			subnetMask := matches[len(matches)-1]

			if subnetMask != "8" {
				return nil, errors.New("Expected to only encounter /8 as the subnet mask, found: " + subnetMask + " in IP range: " + ip)
			}

			if ipParts[1] != "0" || ipParts[2] != "0" || ipParts[3] != "0" {
				return nil, errors.New("Expected to only encounter 0.0.0 in the last three octets, found: " + ipParts[1] + "." + ipParts[2] + "." + ipParts[3] + " in IP range: " + ip)
			}

			sb.WriteString("\t\t\"" + ipParts[0] + "\": {\n")
			for _, server := range service.Servers {
				sb.WriteString("\t\t\t\"" + server + "\",\n")
			}
			sb.WriteString("\t\t},\n")
		}
	}

	template := []byte(`
		package ipv4

        // DO NOT EDIT!
		//
		// This file is generated by internal/cmd/generate-ipv4-bootstrap.go

		// Bootstrap is the IPv4 RDAP bootstrap data sourced from IANA.
		//
		// Source (version: ` + bootstrapResponse.Version + `, publication date: ` + bootstrapResponse.Publication.Format(time.RFC3339) + `): https://data.iana.org/rdap/ipv4.json
		var Bootstrap = map[string][]string{
			` + sb.String() + `
		}
	`)

	return format.Source(template)
}
