package main

import (
	"go/format"
	"log"
	"os"
	"strings"
	"time"

	"github.com/ryanmab/rdap-go/internal/cmd/internal/bootstrap"
	"github.com/ryanmab/rdap-go/internal/query"
)

func main() {
	outputPath := "internal/registry/internal/asn/bootstrap_generated.go"

	bootstrapResponse := bootstrap.FetchBootstrap(query.AsnQuery)

	log.Printf("Fetched ASN bootstrap data version %s published at %s. There are %d services", bootstrapResponse.Version, bootstrapResponse.Publication, len(bootstrapResponse.Services))

	f, err := os.Create(outputPath)

	if err != nil {
		log.Fatal(err)
	}

	template, err := generate(bootstrapResponse)

	if err != nil {
		log.Fatal(err)
	}

	if _, err := f.Write(template); err != nil {
		log.Fatal(err)
	}

	if err := f.Close(); err != nil {
		log.Fatal(err)
	}

	log.Printf("Wrote ASN bootstrap data to %s", outputPath)
}

func generate(bootstrapResponse bootstrap.Response) ([]byte, error) {
	var sb strings.Builder
	for _, service := range bootstrapResponse.Services {
		for _, asnRange := range service.Keys {
			asnStart, asnEnd, found := strings.Cut(asnRange, "-")

			if found {
				sb.WriteString("\t\t{" + asnStart + ", " + asnEnd + "}: {\n")
			} else {
				sb.WriteString("\t\t{" + asnStart + ", " + asnStart + "}: {\n")
			}

			for _, server := range service.Servers {
				sb.WriteString("\t\t\t\"" + server + "\",\n")
			}
			sb.WriteString("\t\t},\n")
		}
	}

	template := []byte(`
		package asn

        // DO NOT EDIT!
		//
		// This file is generated by internal/cmd/asn/main.go

		// Bootstrap is the ASN RDAP bootstrap data sourced from IANA.
		//
		// Source (version: ` + bootstrapResponse.Version + `, publication date: ` + bootstrapResponse.Publication.Format(time.RFC3339) + `): https://data.iana.org/rdap/asn.json
		var Bootstrap = map[[2]uint32][]string{
			` + sb.String() + `
		}
	`)
	return format.Source(template)

}
